import { desc, gte, sql } from "drizzle-orm";
import { Eye, MousePointerClick, Newspaper, Users } from "lucide-react";

import { requireAdminUser } from "@/src/admin/permissions";
import { dateDaysAgo } from "@/src/admin/shared";
import { getDb } from "@/src/db";
import { articleViewDailyStats, articleViews, articles } from "@/src/db/schema";

export default async function AnalyticsAdminPage({ searchParams }: { searchParams: Promise<{ days?: string }> }) {
  await requireAdminUser("analytics:view"); const { days: daysParam = "30" } = await searchParams; const days = [7, 30, 90].includes(Number(daysParam)) ? Number(daysParam) : 30; const start = dateDaysAgo(days); const startDay = start.toISOString().slice(0, 10); const db = await getDb();
  const [summary, unique, top, daily] = await Promise.all([db.select({ views: sql<number>`coalesce(sum(${articleViewDailyStats.views}), 0)`, visitors: sql<number>`coalesce(sum(${articleViewDailyStats.uniqueVisitors}), 0)` }).from(articleViewDailyStats).where(gte(articleViewDailyStats.day, startDay)), db.select({ count: sql<number>`count(distinct ${articleViews.visitorHash})` }).from(articleViews).where(gte(articleViews.viewedAt, start)), db.select({ id: articles.id, title: articles.title, slug: articles.slug, views: sql<number>`coalesce(sum(${articleViewDailyStats.views}), 0)` }).from(articleViewDailyStats).innerJoin(articles, sql`${articleViewDailyStats.articleId} = ${articles.id}`).where(gte(articleViewDailyStats.day, startDay)).groupBy(articles.id).orderBy(desc(sql`coalesce(sum(${articleViewDailyStats.views}), 0)`)).limit(10), db.select({ day: articleViewDailyStats.day, views: sql<number>`sum(${articleViewDailyStats.views})`, visitors: sql<number>`sum(${articleViewDailyStats.uniqueVisitors})` }).from(articleViewDailyStats).where(gte(articleViewDailyStats.day, startDay)).groupBy(articleViewDailyStats.day).orderBy(articleViewDailyStats.day)]);
  const max = Math.max(1, ...daily.map((item) => Number(item.views)));
  return <><header className="admin-page-header"><div><span className="admin-eyebrow">Audience intelligence</span><h1>Analytics</h1><p>Publication traffic and story performance for the last {days} days.</p></div><form className="admin-range-picker"><select name="days" defaultValue={String(days)}><option value="7">7 days</option><option value="30">30 days</option><option value="90">90 days</option></select><button>Apply</button></form></header><section className="admin-stat-grid"><div className="admin-stat-card blue"><div><span>Article views</span><strong>{Number(summary[0]?.views ?? 0).toLocaleString()}</strong><small>Selected period</small></div><Eye size={22} /></div><div className="admin-stat-card green"><div><span>Unique visitors</span><strong>{Number(unique[0]?.count ?? summary[0]?.visitors ?? 0).toLocaleString()}</strong><small>Hashed visitors</small></div><Users size={22} /></div><div className="admin-stat-card amber"><div><span>Top story views</span><strong>{Number(top[0]?.views ?? 0).toLocaleString()}</strong><small>Best performer</small></div><Newspaper size={22} /></div><div className="admin-stat-card red"><div><span>Stories tracked</span><strong>{top.length}</strong><small>With recent traffic</small></div><MousePointerClick size={22} /></div></section><section className="admin-dashboard-grid analytics"><div className="admin-card admin-chart-card"><div className="admin-section-heading"><div><span className="admin-eyebrow">Trend</span><h2>Daily traffic</h2></div></div><div className="admin-bar-chart">{daily.map((item) => <div key={item.day} title={`${item.day}: ${item.views} views`}><span style={{ height: `${Math.max(3, Number(item.views) / max * 100)}%` }} /><small>{item.day.slice(5)}</small></div>)}</div>{daily.length === 0 ? <p className="admin-empty">No view data in this period.</p> : null}</div><div className="admin-card"><div className="admin-section-heading"><div><span className="admin-eyebrow">Ranking</span><h2>Top stories</h2></div></div><ol className="admin-ranking">{top.map((item, index) => <li key={item.id}><span>{String(index + 1).padStart(2, "0")}</span><a href={`/articles/${item.slug}`} target="_blank">{item.title}</a><strong>{Number(item.views).toLocaleString()}</strong></li>)}</ol></div></section></>;
}
