import { asc, desc } from "drizzle-orm";
import { Copy, UserPlus } from "lucide-react";

import { SubmitButton } from "@/components/admin/submit-button";
import { inviteUser, issueSetupLink, updateUser } from "@/src/admin/operations-actions";
import { requireAdminUser } from "@/src/admin/permissions";
import { humanize } from "@/src/admin/shared";
import { getDb } from "@/src/db";
import { userRoleValues, users, userStatusValues } from "@/src/db/schema";

export default async function UsersAdminPage({ searchParams }: { searchParams: Promise<{ invite?: string }> }) {
  const actor = await requireAdminUser("users:manage"); const { invite } = await searchParams; const db = await getDb();
  const rows = await db.query.users.findMany({ columns: { id: true, name: true, email: true, role: true, status: true, createdAt: true, updatedAt: true }, orderBy: [desc(users.createdAt), asc(users.name)] });
  const roles = actor.role === "SUPER_ADMIN" ? userRoleValues : userRoleValues.filter((role) => role !== "SUPER_ADMIN");
  return <><header className="admin-page-header"><div><span className="admin-eyebrow">Access control</span><h1>Users & staff</h1><p>Invite staff, assign responsibilities and revoke access immediately.</p></div></header>{invite ? <div className="admin-invite-banner"><div><UserPlus size={20} /><span><strong>One-time setup link created</strong><small>Share this securely. It expires automatically.</small></span></div><code>{invite}</code><button type="button" title="Select and copy the link manually"><Copy size={16} />Copy link</button></div> : null}<section className="admin-card admin-form-section"><div className="admin-section-heading"><div><span className="admin-eyebrow">New account</span><h2>Invite staff member</h2></div></div><form action={inviteUser} className="admin-form-grid four"><label>Name<input name="name" minLength={2} required /></label><label>Email<input name="email" type="email" required /></label><label>Role<select name="role" defaultValue="AUTHOR">{roles.map((role) => <option key={role} value={role}>{humanize(role)}</option>)}</select></label><SubmitButton>Create invitation</SubmitButton></form></section><section className="admin-user-list">{rows.map((user) => { const protectedUser = user.role === "SUPER_ADMIN" && actor.role !== "SUPER_ADMIN"; return <article className="admin-card admin-user-row" key={user.id}><div className="admin-user-identity"><div className="admin-user-avatar">{(user.name ?? user.email).slice(0, 2).toUpperCase()}</div><div><strong>{user.name ?? "Unnamed account"}</strong><span>{user.email}</span><small>Created {new Date(user.createdAt).toLocaleDateString()}</small></div></div><form action={updateUser.bind(null, user.id)} className="admin-form-grid user"><label>Name<input name="name" defaultValue={user.name ?? ""} disabled={protectedUser} /></label><label>Role<select name="role" defaultValue={user.role} disabled={protectedUser}>{roles.map((role) => <option key={role}>{role}</option>)}</select>{protectedUser ? <input type="hidden" name="role" value={user.role} /> : null}</label><label>Status<select name="status" defaultValue={user.status} disabled={protectedUser}>{userStatusValues.map((status) => <option key={status}>{status}</option>)}</select>{protectedUser ? <input type="hidden" name="status" value={user.status} /> : null}</label><SubmitButton>Save account</SubmitButton></form><form action={issueSetupLink.bind(null, user.id)}><SubmitButton>Reset link</SubmitButton></form></article>; })}</section></>;
}
